### ISSUE TITLE
Capn Proto tooling

### ISSUE THREAD

**Issue by MostAwesomeDude** [monte-language/typhon#162]
There are several pieces of tooling we need:

* [x] A module in the common library which understands how to navigate binary Capn segments, can serialize and deserialize based on schemata, and can emit Monte code which represents schemata
* [ ] A `capnpc-monte` executable which Typhon will provide, which invokes the common library module in order to compile Capn schemata into Monte modules
* [ ] A higher-order RPC module which can speak the Capn RPC given appropriate schemata

Capn's RPC is quite similar to CapTP, so perhaps it will serve as a useful stopgap. They certainly use familiar terminology.

**Comment by justinnoah** [comment]
For reference:
https://capnproto.org/

**Comment by MostAwesomeDude** [comment]
I have been working on the first part of this subsystem in the `capn` branch.

**Comment by dckc** [comment]
I picked up work on this but ran into #182. I can probably fix that...

**Comment by MostAwesomeDude** [comment]
Work continues on the master branch. We are close to having a plugin for `capnpc`.

**Comment by dckc** [comment]
@MostAwesomeDude bootstrapped capn (2c39756) and I reproduced his results

simpson:
>  `./mt-typhon -l mast -l . loader run tools/capnpc <meta.capn >bootstrap.mast`
> You should only have to $(make) first.
> And then `$(cp bootstrap.mast mast/capn/)` should let you run it again.
> And then, for S&G, `$(sha256sum bootstrap.mast mast/capn/bootstrap.mast)`


`make -j 6` crunches away... win: `~/projects/typhon$ ~/.nix-profile/mt-typhon -l mast -l . loader run tools/capnpc <meta.capn >bootstrap.mast`

simpson
> Did it take only a few seconds and write MAST to bootstrap.mast?

DanC
> yes

simpson
> Great! You can inspect that with $(monte dump-mast bootstrap.mast) BTW, if your Monte CLI is new enough.

DanC
> dump-mast seems happy...
> object ::"c++/src/capnp/schema.capnp:CodeGeneratorRequest"

DanC
> by "run it again" did you mean exactly the same command?

simpson
> Well, for maximum fun, try copying that file to mast/capn/ so that it overwrites what the Makefile built.
> And then run capnpc again and see if it succeeds again.

DanC
> $ sha256sum bootstrap.mast mast/capn/bootstrap.mast 
 f310a9ec63c636c4fe8063d9cf4aa48ea1d7a67a59be9936bd5646fddc8ae99a  bootstrap.mast
f310a9ec63c636c4fe8063d9cf4aa48ea1d7a67a59be9936bd5646fddc8ae99a  mast/capn/bootstrap.mast

simpson
> Hey, I have that same combination on my bootstrap.mast!

DanC
> now... what is it that I reproduced? how do we use it?

simpson
> Well, lemme explain what the Capn toolchain wants.
 The $(capnpc) compiler expects a flag, like $(capnpc -omonte-mast), to indicate what to output. Internally, this means that it'll look for an executable on $PATH called `monte-mast-capnpc`, and it'll pipe a CodeGeneratorRequest to stdin and return whatever's piped to stdout.
 Nix can generate wrapper executables. We'd be installing a new binary wrapper.
 And this piece is the penultimate piece. It takes in a CodeGeneratorRequest on stdin and vomits MAST to stdout.


## Appendix: bumps along the way

### Stale TLS cert

symptoms: `.nix-profile/bin/nix-channel: unable to check ‘https://hydra.matador.cloud/project/monte/channel/latest’`

### Struggled to install current monte, typhonVm due to ancient nix

symptoms:

```$ nix-env -i monte
 error: syntax error, unexpected $undefined, expecting IND_STR or DOLLAR_CURLY or IND_STRING_CLOSE, at /nix/store/r3lxhi5xz2mqshis956skc3n94483lii-nixpkgs-18.03pre120540.b8f7027360/nixpkgs/pkgs/applications/misc/hubstaff/default.nix:30:77
```

lose: `Name typhonAstEval has no scope` https://gist.github.com/dckc/a692c0d29b9db8fd05ccf4551782f12d

7l1dfw306hxz4gcc6cp59aiikifbbdrp-typhon-vm -> https://hydra.matador.cloud/build/5392 -> typhon 805380 to 2c3975

**Comment by MostAwesomeDude** [comment]
We have progressed to the point where individual issues should be filed to improve Capn Proto support. The basics are present and, while they might not be perfect, any new implementation will surely want to crib heavily from what we've gotten done so far.
