### ISSUE TITLE
Proper spans for braces/indents syntax errors

### ISSUE THREAD

**Issue by washort** [monte-language/typhon#180]
def foo := [
        def bla() {
                if (a):
                    b
        }
    ]

`example.mt:2.13-2.14: No matching ] found`

Should be `3.19-3.20: Indented blocks only allowed in statement position`

**Comment by dckc** [comment]
What is "statement position"?

I have [a todo in the Lexical grammar section of the docs](http://monte.readthedocs.io/en/latest/symbols.html#index-1) for "specify `canStartIndentedBlock`, `braceStack` exactly"

I tried a few specifications in haskell code but I don't think I found one that's consistent with the available monte code. I don't recall exactly which monte exampled didn't work, unfortunately. What I tried was:

  - [offside in Masque/Lexer.hs from Nov 24, 2015](https://github.com/dckc/masque/blob/e418c07d8523a7b244c8653b023abcd615c60507/Masque/Lexer.hs#L85-L118)
  - [indentparser from hackage](https://hackage.haskell.org/package/indentparser-0.1/docs/Text-Parsec-IndentParsec.html)

**Comment by washort** [comment]
Basic idea is: top-level expressions can use indent syntax, expressions inside indent-syntax blocks can use indent syntax, everything else has to use braces.

**Comment by dckc** [comment]
... which begs the following questions:

- What's a top-level expression?
- What does it mean for an expression to use indent syntax?
- What does it mean for an expression to be inside indent-syntax?

Surely being "top-level" isn't a property of an expression in the AST sense. The integer literal expression 123 is identical to every other integer literal expression 123; either all of them are top-level or none of them are (that is: either it is or it isn't). So when we say "expression" here, we probably mean something like "the tokens that get parsed as an expression". In fact, I wonder if talking about expressions is really useful at all here.

I think to use indent syntax means to let `:` to stand for `{`, newline stand for `;`, and dedent stand for `}`. The lexer seems to keep a brace stack. To be inside indent-syntax means for the top of the brace stack to be `:` rather than `{`. Something like that.

**Comment by washort** [comment]
Yes, this is a concrete-syntax issue and isn't directly expressed in the AST. The pretty-printer keeps track of it, though.

In practical terms, "top-level expression" means "whatever is at the root of the parse done by `parseExpression` or the expression inside a module".
