### ISSUE TITLE
compile server

### ISSUE THREAD

**Issue by dckc** [monte-language/typhon#24]
The monte dev workflow is sort of tediously slow these days. I wonder how much of that is due to compiler start-up time. The compiler seems ideally suited to work as a server.

Here's hoping for time to code it up.

p.s. Python habits die hard... is the goal to eventually have monte automatically compile .mt to .ty on demand like python does for .py to .pyc?

**Comment by CorbinSimpsonAcquia** [comment]
The short answer is that I don't know why startup is slow, aside from obvious problems like AST node reflection across the RPython-Monte boundary. RPython upstream is currently sprinting for vmprof, which will answer quite a bit of this for us.

A compilation server is a fun-sounding idea, but at least for current corpus, compile time is dominated by the parser. A 4s tax on startup is not much compared to 30s of parser time.

Automatic compilation for files would be fine, although I wouldn't be surprised to hear @washort espousing workflows that don't involve any filesystem access at all. Also, unlike (most) Python implementations, Typhon doesn't have its own compiler and I'm really not interested in building one. Running Monte is enough of a full-time job.

**Comment by dckc** [comment]
Running monte is all I had in mind.

**Comment by MostAwesomeDude** [comment]
I think, but am not sure, that most startup time is due to auditors and node reflection. If that's true, then removing node reflection will help immensely.

Compiling as a server would shave ~4s off of recompiles, but the average recompile takes ~20s on my machine (geometric, back of napkin), so I'm not super-sure if the benefit is there. I do see your point.

Typhon won't compile-on-demand, but perhaps a more integrated environment would have that option.

**Comment by dckc** [comment]
We now have a repl-server and `mt run` does compile on demand.
