### ISSUE TITLE
Allow writing MAST output to stdout

### ISSUE THREAD

**Issue by justinnoah** [monte-language/typhon#55]
monstrosite is accepting MAST from stdin. It would be nice to one line chain typhon with monstrosite.

E.g.:

```
typhon -l boot boot/montec hello_world.mt | monstrosite -o hello_world
```

**Comment by justinnoah** [comment]
This will require quieting all other stdout output as well, which may be a bigger problem to tackle than I realized.

**Comment by dckc** [comment]
gee... if only there were a discipline for making sure access to thinks like stdout was explicitly passed to all parts of a program that uses it ;-)

That is: I was a bit surprised to see that typhon doesn't use ocap discipline internally.
e.g. http://www.madmode.com/2013/python-capability-idioms-part-1.html

simpson explained why it's not practical for some things, but I think I/O is not one of them.

**Comment by MostAwesomeDude** [comment]
There is not much stdout stuff left, and I'll take patches on what's not there yet.

It's not possible, without doing a *lot* of RPython hacking, to prevent print statements from being accidentally checked in. It's also not possible to suppress things like RPython exceptions from being printed out to stdout.

I encourage the standard Typhon logging module for logging internal things of interest. It only writes to stderr and can be tuned via CLI flags.

Aside from this bit, the actual work to make montec write to stdout is not hard. Adapt montec to write its logging messages to stderr instead of stdout, and then add logic to recognize "-" as a proxy for stdout. (Or, alternatively, be on Linux and use "/dev/stdout".) I will take patches on that independently from patches that change RPython logging.

**Comment by MostAwesomeDude** [comment]
I just checked, and the REPL is stdout-clean; it prints to stdout only what you send it and any tracebacks from code that you send it. I anticipate that montec is almost as acceptable, except for its logging which prints to stdout.

**Comment by MostAwesomeDude** [comment]
Kicking this out of the sprint.

**Comment by MostAwesomeDude** [comment]
Feature is done.
