### ISSUE TITLE
tracebacks show everything the module loader passes to main

### ISSUE THREAD

**Issue by dckc** [monte-language/typhon#62]
```
Taking initial turn in script...
Log: (vat:serious) Vat pa: Uncaught user exception while taking turn (and no resolver): Exception in user code:
In <whenResolvedReactor>.Atom(run/1) [[["main" => <main>], moduleConfiguration([].asMap())]]:
In <_>.Atom(run/1) [[["main" => <main>], moduleConfiguration([].asMap())]]:
In M.Atom(call/4) [<main>, "run", [["hello.mt"]], ["null" => null, "Infinity" => Infinity, "NaN" => NaN, "false" => false, "true" => true, "Any" => Any, "Binding" => <BindingGuard>, "DeepFrozen" => DeepFrozen, "Near" => <nearGuard>, "Same" => Same, "Selfless" => <Selfless>, "SubrangeGuard" => SubrangeGuard, "M" => M, "Ref" => <Ref>, "_auditedBy" => <auditedBy> ...
```

my nix/store version is `hggrg019hcdxmvpz4qc9cpik5r9k5v9w-typhon`

**Comment by dckc** [comment]
I wonder if this is fixed in 646c9dc8f291b65a4d5d8471d1f210b7322f0e7f

**Comment by MostAwesomeDude** [comment]
No, this log message is produced by Typhon itself, in response to a queued turn that ended in an exceptional state with no resolver to hand the exception to.

This isn't a problem, generally, since Typhon's logs are intended for debugging and can see the entire VM state. Inside Monte, this is still protected by the sealed-exception mechanism.

Was there a concrete problem with this behavior? I very much intended for VM tracebacks to be full of all of the useful information that one needs to debug problems.

**Comment by dckc** [comment]
I don't see these symptoms any more.

`6gswvazlcimjjxx56awbh0l9i2ij1y3f-mt/bin/mt`
