### ISSUE TITLE
are sets ordered?

### ISSUE THREAD

**Issue by dckc** [monte-language/typhon#93]
This is surprising:
```
▲> [1, 2].asSet() == [2, 1].asSet()
Result: false
```

Is that by design?

One alternative would be for asSet() to do like sortKeys(); somewhat ironically, this would require that all elements of a set be comparable, so that ["1", 1].asSet() would fail.

The only other alternative I see for extensional sets is where == is O(n^2).

version: q7qc3b6nygjn3wg2fvgn1lfi07cbg38g-mt

**Comment by MostAwesomeDude** [comment]
Marking as semantics, since apparently this isn't clearly documented.

Sets are intentionally ordered, as are maps. The rationale is that we would like for iteration order to be deterministic and we do not want to require a total ordering on all objects; i.e. we want sets like ``[1, 'a', NaN].asSet()`` to be legal.

Our sameness test ``x == y``, on sets, is O(kn) where n is the shorter set's size and k is the cost of the sameness test (probably amortized O(1) but I'm not confident on that.)

As for the comparison test ``x <=> y``... Hm. Well, we'll more generally want to do ``x.op__cmp(y)``. Which comparison should this implement? Well, IMO it should be the subset test. ``x <= y`` means that x is a subset of y, and ``x < y`` is a strictly smaller subset.

I thought about it for a bit, and here's a sketch of the algorithm which should be amortized O(kn) (worst case O(kn**2)), where again n is the shorter set's size and k is the cost of the sameness test.

* O(1): Pick the shorter set.
* O(n): For each item in the shorter set...
 * Amortized O(1), worst case O(n): Check whether the item is in the larger set. If not, then return; they're incomparable.
* O(1): The smaller set is a subset of the larger set. Check whether the sets are the same size; if they are, then the smaller set is also <=> the larger set.
